name: Clone Traffic Tracker

on:
  workflow_dispatch:  # Manual triggering
  schedule:
    - cron: "0 0 * * 1"  # Automated schedule (every 2 weeks on Monday)

jobs:
  track-clone-traffic:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Clone Statistics
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/traffic/clones"
          
      - name: List Files in Workspace
        run: ls -R
        
      - name: Commit the results to the repo
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add -f clone_traffic.log
         git commit --allow-empty -m "add traffic logs"
         git push
